default:
  before_script:
    - ansible-galaxy install -r requirements.yml

provision-s3-buckets:
  image: lexauw/ansible-alpine
  script:
    - ansible-playbook s3-buckets.yml
  cache:
    paths:
      - .imported_roles
  when: manual
