default:
  before_script:
    - ansible-galaxy install -r requirements.yml

provision-s3-buckets:
  image: lexauw/ansible-alpine
  script:
    - echo $ANSIBLE_VAULT_PASSWORD_FILE
    - ansible-config dump | grep VAULT
    - ansible-playbook s3-buckets.yml
  cache:
    paths:
      - .imported_roles
  only:
    - web  #trigger this manually

