stages:
  - prebuild
  - provisions

#default:
#  stage: prebuild
#  image: lexauw/ansible-alpine
#  before_script:
#    - ansible-galaxy install -r requirements.yml
#  cache:
#    paths:
#      - .imported_roles
#  when: manual

##provision-s3-buckets:
#  script:
#    - ansible-playbook s3-buckets.yml

build-postgres-image:
  stage: prebuild
  image: tmaier/docker-compose:18.09
  services:
    - docker:18.09-dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - apt-get install git-crypt
    - git-crypt unlock
    - docker-compose build
  when: always

#provision-postgres-server:
#  stage: provision
#  script:
#    - ansible-playbook ec2-postgis-server.yml
#  dependencies:
#    - build-postgres-image