stages:
  - build
  - deploy


#default:
#  stage: prebuild
#  image: lexauw/ansible-alpine
#  before_script:
#    - ansible-galaxy install -r requirements.yml
#  cache:
#    paths:
#      - .imported_roles
#  when: manual

##provision-s3-buckets:
#  script:
#    - ansible-playbook s3-buckets.yml

build-postgres-image:
  stage: build
  image: ecohealthalliance/docker-compose-git-crypt
  services:
    - docker:19.03.1-dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
  before_script:
    - gitlab-ci/build_before.sh
  script:
    - gitlab-ci/build.sh
  when: always

# test comment
deploy-app:
  stage: deploy
  image: ecohealthalliance/docker-compose-git-crypt
  when: manual
  services:
    - docker:19.03.1-dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
  before_script:
    - gitlab-ci/deploy_before.sh
  script:
    - gitlab-ci/deploy.sh
