---
- hosts: repel-aws
  tasks:
    - name: copy .env file
      become: yes
      copy:
        src: ./.env
        dest: "/root/docker"
        owner: root
        group: root
        mode: 0755
    - name: Get env file content
      become: yes
      slurp:
        src: /root/docker/.env
      register: env_file_content
    - name: Parse env file and load into fact
      become: yes
      set_fact:
        env_vars: "{{ ('{' + (env_file_content.content | b64decode).split('\n') | select | map('regex_replace', '([^=]*)=(.*)', '\"\\1\": \"\\2\"') | join(',') + '}') | from_json }}"
    - name: install system packages
      become: yes
      apt:
        name:
          - python3-pip
          - python3-setuptools
          - python3-pexpect
          - unzip
        state: present
        update_cache: yes
    - name: add docker gpg apt key
      become: yes
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: add docker repo
      become: yes
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
    - name: update apt and install docker-ce
      become: yes
      apt: update_cache=yes name=docker-ce state=present
    - name: install Docker module for Python
      become: yes
      pip:
        name:
          - docker
          - docker-compose
    - name: create directory
      become: yes
      file:
        path: "{{ env_vars['PRODUCTION_BASE_DOCKER_DIR'] }}"
        state: directory
        owner: root
        group: root
        mode: 0775
    - name: copy service directories and files to host
      become: yes
      copy:
        src: "./{{ item }}"
        dest: "{{ env_vars['PRODUCTION_BASE_DOCKER_DIR'] }}"
        owner: root
        group: root
        mode: 0755
      loop:
        - "cron"
        - "nginx"
        - "plumber"
        - "postgres"
        - "rshinyauth0"
        - "scraper"
        - "shiny"
        - "docker-compose-local.yml"
        - "docker-compose-minlocal.yml"
        - "docker-compose-production.yml"
        - "docker-compose-production-aws.yml"
        - "docker-compose.yml"
        - "Dockerfile.base"
    - name: log into docker registry
      become: yes
      docker_login:
        registry: "{{ env_vars['DOCKER_REGISTRY'] }}"
        username: "{{ env_vars['DOCKER_REGISTRY_USER'] }}"
        password: "{{ env_vars['DOCKER_REGISTRY_PASSWORD'] }}"
        reauthorize: yes
    - name: deploy docker-compose stack
      become: yes
      docker_compose:
        project_src: "{{ env_vars['PRODUCTION_BASE_DOCKER_DIR'] }}"
        state: present
        debug: yes
        files:
          - docker-compose.yml
          - docker-compose-production-aws.yml
