version: '3'

services:
  postgres:
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432"
    environment:
      - IS_PROD=yes
  cron:
    environment:
      - IS_PROD=yes
    volumes:
      - /var/log/repel:/var/log/shared
  shinyserver:
    volumes:
      - /var/log/repel:/srv/repel-shiny-server/logs
      - /home/repeluser/reports:/srv/repel-shiny-server/reports
  scraper:
    volumes:
      - /var/log/repel:/var/log/shared
      - /home/repeluser/reports:/home/rstudio/repel-infrastructure/scraper/reports/
  nginx:
    environment:
      IS_LOCAL: "no"
      STAGING: "false"
      URL: ${NGINX_URL}
      EMAIL: ${ADMIN_EMAIL}
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/swag_config:/config
