version: '3'

services:
  postgres:
    ports:
      - '${POSTGRES_EXTERNAL_PORT}:5432'
  cron:
    environment:
      - BACKUP_FLAG=no
  scraper:
    ports:
      - 8787:8787
    environment:
      - SCRAPER_HOST=${POSTGRES_HOST}
      - SCRAPER_PORT=${POSTGRES_PORT}
      - SCRAPER_USER=${POSTGRES_USER}
      - SCRAPER_PASSWORD=${POSTGRES_PASSWORD}
      - SCRAPER_DBNAME=${POSTGRES_DB}
