version: '3'

services:
  postgres:
    ports:
      - '${POSTGRES_EXTERNAL_PORT}:5432'
  cron:
    environment:
      - BACKUP_FLAG=yes
    volumes:
      - /var/log/repel:/var/log/shared      
  shinyserver:
    volumes:
      - /var/log/repel:/srv/shiny-server/logs
  nginx:
    environment:
      - STAGING=true
