version: '3'

services:
  postgres:
    ports:
      - '${POSTGRES_EXTERNAL_PORT}:5432'
  cron:
    environment:
      - BACKUP_FLAG=yes
    volumes:
      - /var/log/repel:/var/log/shared
  shinyserver:
    volumes:
      - /var/log/repel:/srv/repel-shiny-server/logs
      - /home/repeluser/reports:/srv/repel-shiny-server/reports
  scraper:
    volumes:
      - /var/log/repel:/var/log/shared
      - /home/repeluser/reports:/home/rstudio/repel-infrastructure/scraper/reports/
  nginx:
    image: registry.gitlab.com/ecohealthalliance/repel-infrastructure/nginx
    build:
      context: './nginx'
    restart: on-failure
    env_file: .env
    environment:
      EMAIL: young@ecohealthalliance.org
      URL: ${HOSTNAME}.ecohealthalliance.org
      IS_LOCAL: "no"
      STAGING: true
    ports:
      - '80:80'
      - '443:443'
    networks:
      - repel-servers
#    volumes:
#      - /home/repeluser/letsencrypt/keys:/etc/letsencrypt/keys
