version: '3'

services:
  postgres:
    ports:
      - '${POSTGRES_EXTERNAL_PORT}:5432'
    environment:
      - WORKFLOW="staging"
  cron:
    environment:
      - WORKFLOW="staging"
    volumes:
      - /var/log/repel:/var/log/shared
  rshinyauth0:
    environment:
      - AUTH0_CALLBACK_URL=https://kirby.ecohealthalliance.org/callback
      - LOGOUT_URL=https://kirby.ecohealthalliance.org
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET_STAGING}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID_STAGING}
  shinyserver:
    volumes:
      - /var/log/repel:/srv/repel-shiny-server/logs
      - /home/repeluser/reports:/srv/repel-shiny-server/reports
  scraper:
    environment:
      - WORKFLOW="staging"
    volumes:
      - /var/log/repel:/var/log/shared
      - /home/repeluser/reports:/home/rstudio/repel-infrastructure/scraper/reports/
  nginx:
    environment:
      STAGING: "false"
      URL: ${NGINX_URL_STAGING}
      EMAIL: ${ADMIN_EMAIL}
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/swag_config:/config
#    volumes:
#      - /home/repeluser/letsencrypt/keys:/etc/letsencrypt/keys
