version: '3'

services:
  postgres:
    ports:
      - '${POSTGRES_EXTERNAL_PORT}:5432'
  cron:
    environment:
      - BACKUP_FLAG=no
  scraper:
    ports:
      - 22097:8787
    environment:
      - SCRAPER_HOST=${POSTGRES_HOST}
      - SCRAPER_PORT=${POSTGRES_PORT}
      - SCRAPER_USER=${POSTGRES_USER}
      - SCRAPER_PASSWORD=${POSTGRES_PASSWORD}
      - SCRAPER_DBNAME=${POSTGRES_DB}
      - USER=${USER}
      - HOME=/home/${USER}
      - USERID=${USERID}
      - GROUPID=${GROUPID}
      - IS_LOCAL=yes
    volumes:
      - $HOME/.ssh:/home/${USER}/.ssh
      - $HOME/.Renviron:/home/${USER}/.Renviron
      - $HOME/.gitconfig:/home/${USER}/.gitconfig
      - $HOME/.gnupg:/home/${USER}/.gnupg
      - $PWD/:/home/${USER}/repel-infrastructure
      - postgres_db_vol:/var/lib/postgresql/data
  nginx:
    environment:
      - STAGING=true
  rshinyauth0:
    ports:
      - 22095:3000
volumes:
  postgres_db_vol:
