version: '3'

services:
  postgres:
    ports:
      - '${POSTGRES_EXTERNAL_PORT}:5432'
    environment:
      - WORKFLOW=local
    volumes:
      - postgres_db_vol:/var/lib/postgresql/data
  cron:
    entrypoint: "bash -c"
    command: "exit 0"
  scraper:
    ports:
      - 22097:8787
    environment:
      - SCRAPER_HOST=${POSTGRES_HOST}
      - SCRAPER_PORT=${POSTGRES_PORT}
      - SCRAPER_USER=${POSTGRES_USER}
      - SCRAPER_PASSWORD=${POSTGRES_PASSWORD}
      - SCRAPER_DBNAME=${POSTGRES_DB}
      - USER=${USER}
      - HOME=/home/${USER}
      - PASSWORD=${RSTUDIO_PASSWORD}
      - USERID=${USERID}
      - GROUPID=${GROUPID}
      - WORKFLOW=local
    volumes:
      - $HOME/.ssh:/home/${USER}/.ssh
      - $HOME/.Renviron:/home/${USER}/.Renviron
      - $HOME/.gitconfig:/home/${USER}/.gitconfig
      - $HOME/.gnupg:/home/${USER}/.gnupg
      - $PWD/:/home/${USER}/repel-infrastructure
      - ./webdocs/logs/:/var/log/shared
      - ./webdocs/reports:/home/rstudio/repel-infrastructure/scraper/reports/
  shinyserver:
    ports:
      - 22090:3838
    volumes:
      - ./webdocs/logs:/srv/repel-shiny-server/logs
      - ./webdocs/reports:/srv/repel-shiny-server/reports
  rshinyauth0:
    entrypoint: "bash -c"
    command: "exit 0"
  nginx:
    entrypoint: "bash -c"
    command: "exit 0"
volumes:
  postgres_db_vol:
