---
- hosts: repel-dev
  tasks:
    - name: Get env file content
      become: yes
      slurp:
        src: /root/docker/.env
      register: env_file_content
    - name: Parse env file and load into fact
      become: yes
      set_fact:
        env_vars: "{{ ('{' + (env_file_content.content | b64decode).split('\n') | select | map('regex_replace', '([^=]*)=(.*)', '\"\\1\": \"\\2\"') | join(',') + '}') | from_json }}"
    - name: bring down docker-compose stack
      become: yes
      docker_compose:
        project_src: "{{ env_vars['DEPLOYMENT_BASE_DOCKER_DIR'] }}"
        state: absent
        debug: yes
        files:
          - docker-compose.yml
          - docker-compose-production.yml
