---
- hosts: localhost
  connection: local
  vars_files:
    - secure.yml
  tasks:
    - name: Create wahis raw data bucket
      s3_bucket:
        aws_access_key: "{{AWS_ACCESS_KEY_ID}}"
        aws_secret_key: "{{AWS_SECRET_ACCESS_KEY}}"
        name: wahis-raw-data
        state: present
        tags:
          project: repel
          manager: Noam Ross

#
# # Create a simple s3 bucket on Ceph Rados Gateway
# - s3_bucket:
#     name: mys3bucket
#     s3_url: http://your-ceph-rados-gateway-server.xxx
#     ceph: true
#
# # Remove an s3 bucket and any keys it contains
# - s3_bucket:
#     name: mys3bucket
#     state: absent
#     force: yes
#
# # Create a bucket, add a policy from a file, enable requester pays, enable versioning and tag
# - s3_bucket:
#     name: mys3bucket
#     policy: "{{ lookup('file','policy.json') }}"
#     requester_pays: yes
#     versioning: yes
#     tags:
#       example: tag1
#       another: tag2
#
# # Create a simple DigitalOcean Spaces bucket using their provided regional endpoint
# - s3_bucket:
#     name: mydobucket
#     s3_url: 'https://nyc3.digitaloceanspaces.com'
#
#   vars_files:
#     - secure.yml