- hosts: repel-aws
  tasks:
    - name: Get env file content
      become: yes
      slurp:
        src: /root/docker/.env
      register: env_file_content

    - name: Parse env file and load into fact
      become: yes
      set_fact:
        env_vars: "{{ ('{' + (env_file_content.content | b64decode).split('\n') | select | map('regex_replace', '([^=]*)=(.*)', '\"\\1\": \"\\2\"') | join(',') + '}') | from_json }}"

    - name: Display environment variables
      become: yes
      environment: "{{ env_vars }}"
      debug:
        msg:
          - "env_vars is {{ env_vars }}"
          - "TZ is {{ env_vars['TZ'] }}"
