version: '3'

services:
  postgres:
    image: registry.gitlab.com/ecohealthalliance/repel-infrastructure/repel-postgres
    build:
      context: './postgres'
    volumes:
       - ./postgres/init:/docker-entrypoint-initdb.d
       - ./postgres/pgconf:/pgconf
    command: postgres -c config_file=/pgconf/postgresql.conf
    ports:
      - '${POSTGRES_EXTERNAL_PORT}:5432'
    env_file: .env
    restart: on-failure
  cron:
    image: registry.gitlab.com/ecohealthalliance/repel-infrastructure/repel-cron
    build:
      context: './cron'
    links:
    - postgres:postgres
    env_file: .env
    restart: on-failure
    depends_on:
      - postgres
  scraper:
    image: registry.gitlab.com/ecohealthalliance/repel-infrastructure/repel-scraper
    build:
      context: './scraper'
    links:
    - postgres:postgres
    env_file: .env
    restart: on-failure
    depends_on:
      - postgres

