---
- hosts: repel-aws
  tasks:
    - name: Get env file content
      become: yes
      slurp:
        src: /root/docker/.env
      register: env_file_content
    - name: Parse env file and load into fact
      become: yes
      set_fact:
        env_vars: "{{ ('{' + (env_file_content.content | b64decode).split('\n') | select | map('regex_replace', '([^=]*)=(.*)', '\"\\1\": \"\\2\"') | join(',') + '}') | from_json }}"
    - name: bring down docker-compose stack
      become: yes
      docker_compose:
        timeout: 300
        project_src: "{{ env_vars['PRODUCTION_BASE_DOCKER_DIR'] }}"
        state: absent
        debug: yes
        files:
          - docker-compose.yml
          - docker-compose-production.yml
    - name: prune everything
      become: yes
      docker_prune:
        timeout: 300
        containers: yes
        images: yes
        images_filters:
          dangling: false
        networks: yes
        volumes: yes
        builder_cache: yes
