name: build-containers

"on": [push]
#  release:
#    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GIT_CRYPT_KEY64: ${{ secrets.GIT_CRYPT_KEY64 }}
    steps:
      - uses: actions/checkout@v1
      - uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Decrypt repository using symmetric key
        run: |
          git stash
          echo $GIT_CRYPT_KEY64 > git_crypt_key.key64 && base64 -d git_crypt_key.key64 > git_crypt_key.key && git-crypt unlock git_crypt_key.key
          rm git_crypt_key.key git_crypt_key.key64
      - uses: c-py/action-dotenv-to-setenv@v2
        with:
          env-file: .env
      - name: Build the containers
        run: docker-compose build
      - name: Push the containers
        run: |
          echo ${DOCKER_PASSWORD | docker login --username ${DOCKER_USER} --password-stdin
          docker-compose push
