name: copy-dev-db-to-prod-bucket

on:
  workflow_dispatch:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ID }}
        aws-secret-access-key: ${{ secrets.AWS_KEY }}
        aws-region: us-east-1

    - name: Copy db backup from dev bucket to production bucket
      run: |
        aws s3 cp s3://repeldb/dumps/repel_backup.dmp.xz s3://repeldb-prod/dumps/repel_backup.dmp.xz
