name: deploy-aws-containers

on:
  workflow_dispatch:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Decrypt repository using symmetric key
        env:
          GIT_CRYPT_KEY64: ${{ secrets.GIT_CRYPT_KEY64 }}
        run: |
          sudo apt-get install git-crypt
          echo $GIT_CRYPT_KEY64 > git_crypt_key.key64 && base64 -d git_crypt_key.key64 > git_crypt_key.key && git-crypt unlock git_crypt_key.key
          rm git_crypt_key.key git_crypt_key.key64
      - name: add dotenv-action
        id: dotenv
        uses: ./.github/actions/dotenv-action
      - name: restrict pem file permissions
        run: |
          chmod 400 repel-aws.pem
      - name: Deploy containers to AWS instance
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deploy-repel-aws.yml
          directory: ./
          inventory: |
            [repel-aws]
            ${{ steps.dotenv.outputs.PRODUCTION_SERVER_URL }} ansible_ssh_private_key_file=${{ steps.dotenv.outputs.PRODUCTION_PEM }} ansible_ssh_user=${{ steps.dotenv.outputs.PRODUCTION_SSH_USER }}
          options: |
            -v
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
