# This is a basic workflow to help you get started with Actions

name: production-update-deploy

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Decrypt repository using symmetric key
        env:
          GIT_CRYPT_KEY64: ${{ secrets.GIT_CRYPT_KEY64 }}
        run: |
          sudo apt-get install git-crypt
          echo $GIT_CRYPT_KEY64 > git_crypt_key.key64 && base64 -d git_crypt_key.key64 > git_crypt_key.key && git-crypt unlock git_crypt_key.key
          rm git_crypt_key.key git_crypt_key.key64
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_KEY }}
          aws-region: us-east-1
      - name: Copy db backup from dev bucket to production bucket
        run: |
          aws s3 cp s3://repeldb/dumps/repel_backup.dmp.xz s3://repeldb-prod/dumps/repel_backup.dmp.xz
      - name: Pull and build containers
        run: |
          export $(egrep -v '^#' .env | xargs)
          echo $DOCKER_REGISTRY_PASSWORD | docker login $DOCKER_REGISTRY -u $DOCKER_REGISTRY_USER --password-stdin
          docker-compose pull || true
          docker-compose build --progress plain
#      - name: Push the containers
#        run: |
#          export $(egrep -v '^#' .env | xargs)
#          echo $DOCKER_REGISTRY_PASSWORD | docker login $DOCKER_REGISTRY -u $DOCKER_REGISTRY_USER --password-stdin
#          docker-compose push
      - name: restrict pem file permissions
        run: |
          chmod 400 repel-aws.pem
      - name: remove containers from AWS instance
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: remove-repel-aws.yml
          directory: ./
          inventory: |
            [repel-aws]
            54.158.127.254 ansible_ssh_private_key_file=repel-aws.pem ansible_ssh_user=ubuntu
          options: |
            -v
      - name: Deploy containers to AWS instance
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deploy-repel-aws.yml
          directory: ./
          inventory: |
            [repel-aws]
            54.158.127.254 ansible_ssh_private_key_file=repel-aws.pem ansible_ssh_user=ubuntu
          options: |
            -v
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PAT: ${{ secrets.GH_PAT }}
