name: test-read-env

on:
  workflow_dispatch:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Decrypt repository using symmetric key
        env:
          GIT_CRYPT_KEY64: ${{ secrets.GIT_CRYPT_KEY64 }}
        run: |
          sudo apt-get install git-crypt
          echo $GIT_CRYPT_KEY64 > git_crypt_key.key64 && base64 -d git_crypt_key.key64 > git_crypt_key.key && git-crypt unlock git_crypt_key.key
          rm git_crypt_key.key git_crypt_key.key64

      - name: add dotenv-action
        id: dotenv
        uses: ./.github/actions/dotenv-action

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo TZ is ${{ steps.dotenv.outputs.TZ }}
